sudo: required

language: cpp
services:
  - docker

before_install:
  # appimagetool
  - wget -nv -c "https://github.com/AppImage/AppImageKit/releases/download/continuous/appimagetool-x86_64.AppImage" -O appimagetool.AppImage

script:
  # archlinux
  - docker build . -f deploydocker/Dockerfile.wine-deploy.archlinux -t wine-appimage.archlinux

after_success:
  - mkdir apps

  # archlinux
  - docker run --rm -v $(pwd)/apps:/tmp/apps -ti wine-appimage.archlinux cp result.tar /tmp/apps
  
  # extract result
  - tar xvf apps/result.tar -C apps
  - rm -rf apps/result.tar

  # md5sum tool
  - wget -c https://github.com/ferion11/libsutil/releases/download/md5sum_util_v0.1/md5sum_util.sh
  - bash md5sum_util.sh apps

  # uploadtool
  - wget -c https://github.com/probonopd/uploadtool/raw/master/upload.sh
  - bash upload.sh apps/*

branches:
  except:
    - # Do not build tags that we create when we upload to GitHub Releases
    - /^(?i:continuous)$/
    - /^release-[0-9a-z\-]*/
    - /^(?i:untagged)-.*$/

notifications:
  email:
    on_success: change # default: change
    on_failure: always # default: always