sudo: required

language: cpp
services:
  - docker

before_install:
  # archlinux
  - wget -nv -c https://github.com/ferion11/libsutil/releases/download/wine_hook_v0.9/libhookexecv.so
  - wget -nv -c https://github.com/ferion11/libsutil/releases/download/wine_hook_v0.9/wine-preloader_hook
#  - wget -nv -c https://www.playonlinux.com/wine/binaries/phoenicis/upstream-linux-x86/PlayOnLinux-wine-4.21-upstream-linux-x86.tar.gz
  - wget -nv -c https://www.playonlinux.com/wine/binaries/phoenicis/staging-linux-x86/PlayOnLinux-wine-4.21-staging-linux-x86.tar.gz
  #- wget -nv -c https://www.playonlinux.com/wine/binaries/phoenicis/upstream-linux-x86/PlayOnLinux-wine-4.10-upstream-linux-x86.tar.gz

  # appimagetool
  - wget -nv -c "https://github.com/AppImage/AppImageKit/releases/download/continuous/appimagetool-x86_64.AppImage" -O appimagetool.AppImage

script:
  # archlinux
  - docker build . -f deploydocker/Dockerfile.wine-deploy.archlinux -t wine-appimage.archlinux

after_success:
  - mkdir apps

  # archlinux
  - docker run --rm -v $(pwd)/apps:/tmp/apps -ti wine-appimage.archlinux cp wine-i386_x86_64-archlinux.AppImage /tmp/apps
  - docker run --rm -v $(pwd)/apps:/tmp/apps -ti wine-appimage.archlinux cp wine-i386_x86_64-archlinux.AppImage.zsync /tmp/apps

  # uploadtool
  - wget -c https://github.com/probonopd/uploadtool/raw/master/upload.sh
  - bash upload.sh apps/*

branches:
  except:
    - # Do not build tags that we create when we upload to GitHub Releases
    - /^(?i:continuous)$/
    - /^release-[0-9a-z\-]*/
    - /^(?i:untagged)-.*$/

notifications:
  email:
    on_success: change # default: change
    on_failure: always # default: always